version: "2"
services:
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins:2.227
        restart: unless-stopped
        networks:
            - nextcloud_network    
        ports:
        - "8080:8080"
        - "50000:50000"
        environment:
            TZ: Europe/Copenhagen
        volumes:
        - ./data:/var/jenkins_home/:rw
        - ./scripts:/var/scripts/:rw
        - ./client/build:/usr/bin/myapp/:ro
        - ./client/settings.yml:/etc/cibroker/settings.yml/:ro
        # disabled until sock binding can be autostarted
        #- $SSH_AUTH_SOCK:/ssh-agent
    node:
        image: shukriadams/node10build:0.0.1
        networks:
            - nextcloud_network
        volumes:
        - ./:/usr/app/:rw
        command: sh -c "cd /usr/app && node slave"
        ports:
        - "8081:8081"

networks:
    nextcloud_network:
        driver: bridge