name: builds
on: 
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: builds
        run: cd src && npm install && cd ../build && npm install && bash ./build.sh --target linux64 --upload 1
